### ISSUE TITLE
quickcheckout is not working with v3

### ISSUE THREAD

**Issue by papppeter** [OFFLINE-GmbH/oc-mall-plugin#1013]
Hi,

component quickcheckout is not working. script fails if error happens. 
after request error has a different markup now

suggested solution is:

in scripts.htm
`
function submit () {
    $form.request('{{ __SELF__ }}::onSubmit', {
        complete: function () {
            handleError();
        },
    })
}
`

this works for me

**Comment by chocolata** [comment]
Hi @papppeter 

I'm seeing something similar. When clicking submit on the quick checkout page, I get an alert:

![image](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/3584586/eea717c5-1ee9-4904-beab-82fd03935170)

In the console, there is just a general 406 error...

Adding the line you provided doesn't seem to work for me...

Did you see the same error message? Could you kindly share your entire submit() function ?

**Comment by majesticmind** [comment]
Hi, 

I got the exact same issue and error as @chocolata described above. I have a clean installation and running latest versions of Mall and OctoberCMS.

Hopefully this bug can be fixed asap.

**Comment by papppeter** [comment]
`
{% put scripts %}
    <script>
        $(function () {
            var $body = $('body')
            var $form = $('.mall-quick-checkout')
            var $overlay = $('.mall-overlay')

            $body.on('click', '.js-mall-checkout', function (e) {
                e.preventDefault()
                $overlay.prependTo($body).show()

                // Run registered callback functions.
                var keys = Object.keys(window.Mall.Callbacks.Checkout)
                if (keys.length > 0) {
                    var callbacks = keys.map(function (handler) {
                        return window.Mall.Callbacks.Checkout[handler]()
                    })
                    Promise.all(callbacks).then(submit).catch(handleError)
                } else {
                    submit()
                }

                function handleError () {
                    const visibleError = $form.find('[data-validate-for].oc-visible:first');
                    if(visibleError.length > 0) {
                        $overlay.hide();
                        visibleError.closest('.mall-quick-checkout__collapsible-element').trigger('click')
                    }
                }

                function submit () {
                    $form.request('{{ __SELF__ }}::onSubmit', {
                        complete: function (data,status,jqXHR) {
                            handleError();
                        },
                    })
                }
            })

            $('.js-mall-toggle-shipping-address').on('click', function () {
                $('.mall-shipping-address').toggle(this.checked);
            })
            $('.js-mall-toggle-guest-signup').on('click', function () {
                $('.mall-quick-checkout__password-inputs').toggle(!this.checked);
            })
            $('.mall-quick-checkout__collapsible-element').on('click', function () {
                $('.mall-quick-checkout__collapsible-element--open').removeClass('mall-quick-checkout__collapsible-element--open');
                $(this).addClass('mall-quick-checkout__collapsible-element--open')
            })
            $('.js-mall-checkout').prop('disabled', true)
            $('.js-mall-toggle-signup-terms').on('click', function () {
                $('.js-mall-checkout').prop('disabled', ! this.checked);
            });
            $.subscribe('mall.address.update', function() {
                var useCountry = $('#billing_country_id')
                if ($('.js-mall-toggle-shipping-address').prop('checked')) {
                    useCountry = $('#shipping_country_id')
                }

                $.request('{{ __SELF__ }}::onRun', {
                    data: { country_id: useCountry.val() },
                    update: {
                       '{{ __SELF__ }}::cart': '.mall-quick-checkout__cart',
                       '{{ __SELF__ }}::shippingmethod': '.mall-quick-checkout__shipping-methods'
                    }
                })
            })
            $body.on('click', '.mall-quick-checkout__payment-methods .mall-quick-checkout__toggle-option', function() {
                window.Mall.Callbacks.Checkout = {}
            })
            $body.on('click', '.js-mall-remove-product', function () {
                $.request('{{ __SELF__ }}::onRemoveProduct', {
                    data: {id: this.dataset.id},
                    update: {'{{ __SELF__ }}::cart': '.mall-cart'},
                    loading: $.oc.stripeLoadIndicator,
                    confirm: '{{ 'offline.mall::frontend.confirm' | trans }}',
                    success: function (data) {
                        this.success(data)
                        $.publish('mall.cart.update', data)
                        $.publish('mall.cart.productRemoved', data)
                    }
                })
            });
        })
    </script>
{% endput %}

`

**Comment by fedorothebowl** [comment]
I got same problem. I notice that start when i modify the file \partials\quickcheckout\addressform.htm. If i restore it.. it works

**Comment by timbradson** [comment]
> I got same problem. I notice that start when i modify the file \partials\quickcheckout\addressform.htm. If i restore it.. it works

Did you made any changes in the addressform.htm file? Because I didn't make any changes and still gives me this 'error' out of the box.

**Comment by fedorothebowl** [comment]
Yes but i dont have modify the old form, when you call the partial do you pass the type on <div class="mall-address-form--{{ type }}">??

You have to use type="billing" or type="shipping"

**Comment by chocolata** [comment]
Hi @fedorothebowl, I checked, but we pass it on correctly. I also tried to update all plugins to the most recent version as Mall v3.0.23 contains some fixes, but the problem seems to persist.

@tobias-kuendig Could you kindly look into this issue?

**Comment by timbradson** [comment]
Also updated to latest version v3.0.23 but I can confirm it doesn't fix this issue. Quite annoying since I want to onboard a new large client on Mall. :(

**Comment by fedorothebowl** [comment]
Actually, the error persists, but I've made some progress. I noticed that it works if you impersonate the user from the backend. I'll continue investigating

**Comment by chocolata** [comment]
Hi guys, did anyone find the solution to this?

**Comment by tobias-kuendig** [comment]
Please try v3.0.24 and see if things are still broken for you.

Thanks to everyone for the report!

**Comment by chocolata** [comment]
Hi @tobias-kuendig 

Thanks so much! I managed to get it working after updating to v3.0.25, but only after removing the scripts.htm file from my custom partial.

Thanks again. I now get an error regarding the payment method (Mollie), but this might be something on my end. I'll investigate further and report back if necessary.

**Comment by chocolata** [comment]
Hi, is anyone now seeing this error?

I feel it is pointing to a construction with an if statement in a for loop, but as far as I can see I removed all of them in my partials. The payment seems to go through perfectly, but the checkout page seems to throw an error.

The error happens on this page `/checkout/payment?return=return&oc-mall_payment_id=nCNyGfGJ`

![image](https://github.com/OFFLINE-GmbH/oc-mall-plugin/assets/3584586/1eafd31f-a428-41b5-9915-0dbc45590807)

I've tried clearing the cache several times. I've also tried reverting to the default quickcheckout component that comes with the plugin, but the error persists.

I'm sorry if this is might be not be connected to the previous issues.

The full stack trace is below.

```
Twig\Error\SyntaxError: Unexpected token "name" of value "if" ("end of statement block" expected) in "__string_template__c8803b07563ce8abf51b81b22a36e882dd8262710bc3f6dceebe719c4a19671e" at line 62. in /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/TokenStream.php:76
Stack trace:
#0 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/TokenParser/ForTokenParser.php(41): Twig\TokenStream->expect()
#1 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/Parser.php(170): Twig\TokenParser\ForTokenParser->parse()
#2 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/TokenParser/ForTokenParser.php(42): Twig\Parser->subparse()
#3 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/Parser.php(170): Twig\TokenParser\ForTokenParser->parse()
#4 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/Parser.php(83): Twig\Parser->subparse()
#5 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/Environment.php(491): Twig\Parser->parse()
#6 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/Environment.php(519): Twig\Environment->parse()
#7 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/Environment.php(351): Twig\Environment->compileSource()
#8 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/Environment.php(402): Twig\Environment->loadTemplate()
#9 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/system/classes/MailManager.php(296): Twig\Environment->createTemplate()
#10 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/system/classes/MailManager.php(287): System\Classes\MailManager->parseTwig()
#11 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/Environment.php(361) : eval()'d code(51): System\Classes\MailManager->renderPartial()
#12 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/Template.php(394): __TwigTemplate_74964187fd623c4ce1b3a5ec582a814b750c64e9a0a427f761ab1f607b71d3ce->doDisplay()
#13 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#14 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#15 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render()
#16 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/system/classes/MailManager.php(297): Twig\TemplateWrapper->render()
#17 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/system/classes/MailManager.php(181): System\Classes\MailManager->parseTwig()
#18 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/system/classes/MailManager.php(195): System\Classes\MailManager->render()
#19 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/system/classes/MailManager.php(154): System\Classes\MailManager->renderTemplate()
#20 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/system/classes/MailManager.php(118): System\Classes\MailManager->addContentToMailerInternal()
#21 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/system/classes/MailManager.php(68): System\Classes\MailManager->addContentToMailer()
#22 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/system/ServiceProvider.php(603): System\Classes\MailManager->addContentFromEvent()
#23 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): System\ServiceProvider->System\{closure}()
#24 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#25 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/october/rain/src/Events/PriorityDispatcher.php(124): Illuminate\Events\Dispatcher->dispatch()
#26 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/october/rain/src/Events/PriorityDispatcher.php(79): October\Rain\Events\PriorityDispatcher->fireEvent()
#27 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): October\Rain\Events\PriorityDispatcher->fire()
#28 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/october/rain/src/Mail/Mailer.php(421): Illuminate\Support\Facades\Facade::__callStatic()
#29 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/october/rain/src/Mail/Mailer.php(80): October\Rain\Mail\Mailer->addContent()
#30 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(554): October\Rain\Mail\Mailer->send()
#31 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Mail\MailManager->__call()
#32 /var/www/vhosts/brightbib.chocolata.be/httpdocs/plugins/offline/mall/classes/jobs/SendOrderConfirmationToCustomer.php(42): Illuminate\Support\Facades\Facade::__callStatic()
#33 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): OFFLINE\Mall\Classes\Jobs\SendOrderConfirmationToCustomer->fire()
#34 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#35 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(291): Illuminate\Queue\SyncQueue->push()
#36 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Queue\QueueManager->__call()
#37 /var/www/vhosts/brightbib.chocolata.be/httpdocs/plugins/offline/mall/classes/events/MailingEventHandler.php(121): Illuminate\Support\Facades\Facade::__callStatic()
#38 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): OFFLINE\Mall\Classes\Events\MailingEventHandler->checkoutSucceeded()
#39 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#40 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/october/rain/src/Events/Dispatcher.php(18): Illuminate\Events\Dispatcher->dispatch()
#41 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): October\Rain\Events\Dispatcher->fire()
#42 /var/www/vhosts/brightbib.chocolata.be/httpdocs/plugins/offline/mall/classes/payments/PaymentRedirector.php(103): Illuminate\Support\Facades\Facade::__callStatic()
#43 /var/www/vhosts/brightbib.chocolata.be/httpdocs/plugins/offline/mall/classes/payments/PaymentRedirector.php(152): OFFLINE\Mall\Classes\Payments\PaymentRedirector->handlePaymentResult()
#44 /var/www/vhosts/brightbib.chocolata.be/httpdocs/plugins/offline/mall/components/QuickCheckout.php(520): OFFLINE\Mall\Classes\Payments\PaymentRedirector->handleOffSiteReturn()
#45 /var/www/vhosts/brightbib.chocolata.be/httpdocs/plugins/offline/mall/components/QuickCheckout.php(202): OFFLINE\Mall\Components\QuickCheckout->handleOffSiteReturn()
#46 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/cms/classes/ComponentBase.php(171): OFFLINE\Mall\Components\QuickCheckout->onRun()
#47 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/cms/classes/CmsCompoundObject.php(175): Cms\Classes\ComponentBase->runLifeCycle()
#48 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/cms/classes/Controller.php(471): Cms\Classes\CmsCompoundObject->runComponents()
#49 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/cms/classes/Controller.php(377): Cms\Classes\Controller->execPageCycle()
#50 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/cms/classes/Controller.php(219): Cms\Classes\Controller->runPage()
#51 /var/www/vhosts/brightbib.chocolata.be/httpdocs/modules/cms/classes/CmsController.php(65): Cms\Classes\Controller->run()
#52 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Cms\Classes\CmsController->run()
#53 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#54 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch()
#55 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#56 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#57 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#58 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#60 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#61 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#62 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#63 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#64 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#65 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#66 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#67 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#68 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#69 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#70 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Pipeline\Pipeline->then()
#71 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack()
#72 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute()
#73 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/october/rain/src/Router/CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute()
#74 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): October\Rain\Router\CoreRouter->dispatch()
#75 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#76 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#77 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#78 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#79 /var/www/vhosts/brightbib.chocolata.be/httpdocs/plugins/vdlp/redirect/classes/RedirectMiddleware.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#80 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Vdlp\Redirect\Classes\RedirectMiddleware->handle()
#81 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#82 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#83 /var/www/vhosts/brightbib.chocolata.be/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#84 /var/www/vhosts/brightbib.chocolata.be/httpdocs/index.php(43): Illuminate\Foundation\Http\Kernel->handle()
#85 {main}
```
