### ISSUE TITLE
Call to undefined method October\Rain\Database\Relations\BelongsTo::all()

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#1145]
Hello.
Mall 3.3.0
Payment fails at (quick) checkout.
I see this arror after clicking "submit payment" - 
`Call to undefined method October\Rain\Database\Relations\BelongsTo::all()`
This is for a virtual product, but failing on physical products too.

```
[2024-06-04 15:27:56] development.ERROR: OFFLINE.Mall: A payment failed. {"data":{"session_id":"x5m1QsAXFCC4YDbJxwo3XFrXUOFjqEUzmFavOA2P", LOTS OF JSON DATA "is_virtual":true,"file_expires_after_days":null,"file_max_download_count":null,"file_session_required":false,"featured":0,"hash_id":"A7oY8dWM","price":{"GBP":"£ 15.00"}},"created_at":"2024-06-04T15:27:56.000000Z","updated_at":"2024-06-04T15:27:56.000000Z","deleted_at":null,"service_options":[]}]},"response":"[object] (BadMethodCallException(code: 0): Call to undefined method October\\Rain\\Database\\Relations\\BelongsTo::all() at \vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\ForwardsCalls.php:71)
[stacktrace]
#0 \vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Relations\\Relation::throwBadMethodCallException('all')
#1 \vendor\\laravel\\framework\\src\\Illuminate\\Support\\Traits\\ForwardsCalls.php(52): Illuminate\\Database\\Eloquent\\Relations\\Relation->forwardCallTo(Object(October\\Rain\\Database\\Builder), 'all', Array)
#2 \vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Relations\\Relation.php(491): Illuminate\\Database\\Eloquent\\Relations\\Relation->forwardDecoratedCallTo(Object(October\\Rain\\Database\\Builder), 'all', Array)
#3 \vendor\\october\\rain\\src\\Database\\Relations\\DefinedConstraints.php(110): Illuminate\\Database\\Eloquent\\Relations\\Relation->__call('all', Array)
#4 \vendor\\october\\rain\\src\\Database\\Relations\\DefinedConstraints.php(23): October\\Rain\\Database\\Relations\\BelongsTo->addDefinedConstraintsToQuery(Object(October\\Rain\\Database\\Relations\\BelongsTo), Array)
#5 \vendor\\october\\rain\\src\\Database\\Relations\\BelongsTo.php(32): October\\Rain\\Database\\Relations\\BelongsTo->addDefinedConstraints()
#6 \vendor\\october\\rain\\src\\Database\\Concerns\\HasRelationships.php(542): October\\Rain\\Database\\Relations\\BelongsTo->__construct(Object(October\\Rain\\Database\\Builder), Object(OFFLINE\\Mall\\Models\\Order), 'customer_paymen...', 'id', 'customer_paymen...')
#7 \vendor\\october\\rain\\src\\Database\\Concerns\\HasRelationships.php(374): October\\Rain\\Database\\Model->belongsTo('OFFLINE\\\\Mall\\\\Mo...', 'customer_paymen...', 'id', 'customer_paymen...')
#8 \vendor\\october\\rain\\src\\Database\\Model.php(290): October\\Rain\\Database\\Model->handleRelation('customer_paymen...')
#9 \vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Concerns\\HasAttributes.php(580): October\\Rain\\Database\\Model->__call('customer_paymen...', Array)
#10 \vendor\\october\\rain\\src\\Database\\Concerns\\HasAttributes.php(83): Illuminate\\Database\\Eloquent\\Model->getRelationshipFromMethod('customer_paymen...')
#11 \plugins\\offline\\mall\\classes\\traits\\JsonPrice.php(76): October\\Rain\\Database\\Model->getAttribute('customer_paymen...')
#12 \vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Model.php(2222): OFFLINE\\Mall\\Models\\Order->getAttribute('customer_paymen...')
#13 \vendor\\october\\rain\\src\\Extension\\ExtendableTrait.php(440): Illuminate\\Database\\Eloquent\\Model->__get('customer_paymen...')
#14 \vendor\\october\\rain\\src\\Database\\Model.php(271): October\\Rain\\Database\\Model->extendableGet('customer_paymen...')
#15 \plugins\\offline\\mall\\classes\\payments\\Stripe.php(65): October\\Rain\\Database\\Model->__get('customer_paymen...')
#16 \plugins\\offline\\mall\\classes\\payments\\DefaultPaymentGateway.php(75): OFFLINE\\Mall\\Classes\\Payments\\Stripe->process(Object(OFFLINE\\Mall\\Classes\\Payments\\PaymentResult))
#17 \plugins\\offline\\mall\\classes\\payments\\PaymentService.php(63): OFFLINE\\Mall\\Classes\\Payments\\DefaultPaymentGateway->process(Object(OFFLINE\\Mall\\Models\\Order))
#18 \plugins\\offline\\mall\\components\\QuickCheckout.php(268): OFFLINE\\Mall\\Classes\\Payments\\PaymentService->process('checkout')
#19 \modules\\system\\traits\\DependencyMaker.php(29): OFFLINE\\Mall\\Components\\QuickCheckout->onSubmit()
#20 \modules\\cms\\classes\\ComponentBase.php(231): Cms\\Classes\\ComponentBase->makeCallMethod(Object(OFFLINE\\Mall\\Components\\QuickCheckout), 'onSubmit')
#21 \modules\\cms\\classes\\controller\\HasAjaxRequests.php(324): Cms\\Classes\\ComponentBase->runAjaxHandler('onSubmit')
#22 \modules\\cms\\classes\\controller\\HasAjaxRequests.php(129): Cms\\Classes\\Controller->runAjaxHandler('quickCheckout::...')
#23 \modules\\cms\\classes\\Controller.php(386): Cms\\Classes\\Controller->execAjaxHandlers()
#24 \modules\\cms\\classes\\Controller.php(226): Cms\\Classes\\Controller->runPage(Object(Cms\\Classes\\Page))
#25 \modules\\cms\\classes\\CmsController.php(72): Cms\\Classes\\Controller->run('checkout')
#26 \vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Controller.php(54): Cms\\Classes\\CmsController->run('checkout')
#27 \vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction('run', Array)
#28 \vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(260): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Cms\\Classes\\CmsController), 'run')
#29 \vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(205): Illuminate\\Routing\\Route->runController()
#30 \vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(798): Illuminate\\Routing\\Route->run()
#31 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 \vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 \vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#36 \vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#37 \vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#38 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 \vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 \vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 \vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(799): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#45 \vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#46 \vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(740): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#47 \vendor\\october\\rain\\src\\Router\\CoreRouter.php(32): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#48 \vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(190): October\\Rain\\Router\\CoreRouter->dispatch(Object(Illuminate\\Http\\Request))
#49 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#50 \plugins\\offline\\speedy\\classes\\middleware\\CDNMiddleware.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): OFFLINE\\Speedy\\Classes\\Middleware\\CDNMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 \plugins\\offline\\speedy\\classes\\middleware\\Http2Middleware.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): OFFLINE\\Speedy\\Classes\\Middleware\\Http2Middleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#54 \plugins\\offline\\responsiveimages\\classes\\ResponsiveImagesMiddleware.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): OFFLINE\\ResponsiveImages\\Classes\\ResponsiveImagesMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 \vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 \vendor\\october\\rain\\src\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(23): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): October\\Rain\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 \plugins\\vdlp\\redirect\\classes\\RedirectMiddleware.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Vdlp\\Redirect\\Classes\\RedirectMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 \vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 \vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#63 \vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#64 \index.php(43): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#65 {main}
","order":{"OFFLINE\\Mall\\Models\\Order":{MORE JSON DATA} 

```

**Comment by SamBrishes** [comment]
Hello,

thanks for reporting this issue. Although the error was in the order model, it only affected the Stripe payment method, PayPal and Invoice continued to function normally.

However, the problem has been fixed now (current next branch). Pull request for v3.3.1 patch is on the way.

Sincerely,\
Sam.
