### ISSUE TITLE
Error when applying discount code "Alternate shipping"

### ISSUE THREAD

**Issue by chocolata** [OFFLINE-GmbH/oc-mall-plugin#1168]
Hi,

I'm noticing that if there's an automatic discount code for free shipping from a specific order amount, an error is thrown and the user cannot checkout:

TypeError: strtoupper(): Argument #1 ($string) must be of type string, null given in `/var/www/vhosts/domain.com/httpdocs/plugins/offline/mall/models/Discount.php:90`

Here is the entire stack trace:

```
TypeError: strtoupper(): Argument #1 ($string) must be of type string, null given in /var/www/vhosts/domain.com/httpdocs/plugins/offline/mall/models/Discount.php:90
Stack trace:
#0 /var/www/vhosts/domain.com/httpdocs/plugins/offline/mall/models/Discount.php(90): strtoupper()
#1 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(421): OFFLINE\Mall\Models\Discount::OFFLINE\Mall\Models\{closure}()
#2 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#3 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(222): Illuminate\Events\Dispatcher->dispatch()
#4 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php(189): Illuminate\Events\Dispatcher->until()
#5 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1122): Illuminate\Database\Eloquent\Model->fireModelEvent()
#6 /var/www/vhosts/domain.com/httpdocs/vendor/october/rain/src/Database/Model.php(383): Illuminate\Database\Eloquent\Model->save()
#7 /var/www/vhosts/domain.com/httpdocs/vendor/october/rain/src/Database/Model.php(425): October\Rain\Database\Model->saveInternal()
#8 /var/www/vhosts/domain.com/httpdocs/plugins/offline/mall/classes/traits/cart/Discounts.php(98): October\Rain\Database\Model->save()
#9 /var/www/vhosts/domain.com/httpdocs/plugins/offline/mall/models/Order.php(217): OFFLINE\Mall\Models\Cart->updateDiscountUsageCount()
#10 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(30): OFFLINE\Mall\Models\Order::OFFLINE\Mall\Models\{closure}()
#11 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(469): Illuminate\Database\Connection->transaction()
#12 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Database\DatabaseManager->__call()
#13 /var/www/vhosts/domain.com/httpdocs/plugins/offline/mall/models/Order.php(222): Illuminate\Support\Facades\Facade::__callStatic()
#14 /var/www/vhosts/domain.com/httpdocs/plugins/offline/mall/components/QuickCheckout.php(258): OFFLINE\Mall\Models\Order::fromCart()
#15 /var/www/vhosts/domain.com/httpdocs/modules/system/traits/DependencyMaker.php(29): OFFLINE\Mall\Components\QuickCheckout->onSubmit()
#16 /var/www/vhosts/domain.com/httpdocs/modules/cms/classes/ComponentBase.php(231): Cms\Classes\ComponentBase->makeCallMethod()
#17 /var/www/vhosts/domain.com/httpdocs/modules/cms/classes/controller/HasAjaxRequests.php(324): Cms\Classes\ComponentBase->runAjaxHandler()
#18 /var/www/vhosts/domain.com/httpdocs/modules/cms/classes/controller/HasAjaxRequests.php(129): Cms\Classes\Controller->runAjaxHandler()
#19 /var/www/vhosts/domain.com/httpdocs/modules/cms/classes/Controller.php(386): Cms\Classes\Controller->execAjaxHandlers()
#20 /var/www/vhosts/domain.com/httpdocs/modules/cms/classes/Controller.php(226): Cms\Classes\Controller->runPage()
#21 /var/www/vhosts/domain.com/httpdocs/modules/cms/classes/CmsController.php(71): Cms\Classes\Controller->run()
#22 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Cms\Classes\CmsController->run()
#23 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction()
#24 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch()
#25 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#26 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#27 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#28 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#30 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#32 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#34 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#35 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#37 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#39 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#40 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Pipeline\Pipeline->then()
#41 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack()
#42 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute()
#43 /var/www/vhosts/domain.com/httpdocs/vendor/october/rain/src/Router/CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute()
#44 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): October\Rain\Router\CoreRouter->dispatch()
#45 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#46 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /var/www/vhosts/domain.com/httpdocs/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#48 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#49 /var/www/vhosts/domain.com/httpdocs/plugins/vdlp/redirect/classes/RedirectMiddleware.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#50 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Vdlp\Redirect\Classes\RedirectMiddleware->handle()
#51 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#52 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then()
#53 /var/www/vhosts/domain.com/httpdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#54 /var/www/vhosts/domain.com/httpdocs/index.php(43): Illuminate\Foundation\Http\Kernel->handle()
#55 {main}
```

If I check that line, it seems like we are incorrectly referencing a discount code, while this isn't relevant in the case of an automatic discount code...

```
        static::saving(function (self $discount) {
            $discount->code = strtoupper($discount->code); // here is the issue
            if ($discount->trigger !== 'product') {
                $discount->product_id = null;
            }
            if ($discount->trigger !== 'code') {
                $discount->code = null;
            }
            if ($discount->trigger !== 'customer_group') {
                $discount->customer_group_id = null;
            }
        });
```

Can we safely do something like the following?

```
    if (!is_null($discount->code)) {
        $discount->code = strtoupper($discount->code);
    }
```

At the moment, it does seem like this little edit allows the clients to go further in the checkout process. Could you kindly review and consider that? Once you've shed a light on it, I'd be happy to make a pull request.

Below you will find how the discount is configured:

![image](https://github.com/user-attachments/assets/f5ff09e5-cb89-48bd-8b4c-a6245ef95ed3)

Best regards and thanks for all your hard work.

**Comment by tobias-kuendig** [comment]
What version are you running? The current version uses this to solve null codes:

https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/70974d90523e7975731e629dfb7303f9f1f356de/models/Discount.php#L115
