### ISSUE TITLE
Expected response code "354" but got code "250", with message "250 2.1.5 Ok".

### ISSUE THREAD

**Issue by dathwa** [OFFLINE-GmbH/oc-mall-plugin#1176]
Hello.
Mall 3.5.4
This error was generated at checkout. The order was created OK.
However, the virtual product in the order, we hook into the `Event::listen('mall.product.file_grant.created', function (ProductFileGrant $grant, Product $product)` event.
When this mail failed, it broke the flow, and it seems the event was never triggered. The user never got their generated ticket, and they were not, in this case, added to a Zoom seminar.

I appreciate this error is buried deep in the mailer code, but any way to force the process to finish, without an exception?

Thanks

```
#0 /public_html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(182): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->assertResponseCode('250 2.1.5 Ok\r\n', Array)
#1 /public_html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(204): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->executeCommand('DATA\r\n', Array)
#2 /public_html/vendor/symfony/mailer/Transport/AbstractTransport.php(69): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->doSend(Object(Symfony\Component\Mailer\SentMessage))
#3 /public_html/vendor/symfony/mailer/Transport/Smtp/SmtpTransport.php(136): Symfony\Component\Mailer\Transport\AbstractTransport->send(Object(Symfony\Component\Mailer\SentMessage), Object(Symfony\Component\Mailer\DelayedEnvelope))
#4 /public_html/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(523): Symfony\Component\Mailer\Transport\Smtp\SmtpTransport->send(Object(Symfony\Component\Mime\Email), Object(Symfony\Component\Mailer\DelayedEnvelope))
#5 /public_html/vendor/october/rain/src/Mail/Mailer.php(126): Illuminate\Mail\Mailer->sendSymfonyMessage(Object(Symfony\Component\Mime\Email))
#6 /public_html/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(554): October\Rain\Mail\Mailer->send('offline.mall::m...', Array, Object(Closure))
#7 /public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Mail\MailManager->__call('send', Array)
#8 /public_html/plugins/offline/mall/classes/jobs/SendOrderConfirmationToCustomer.php(43): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#9 /public_html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): OFFLINE\Mall\Classes\Jobs\SendOrderConfirmationToCustomer->fire(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#10 /public_html/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(43): Illuminate\Queue\Jobs\Job->fire()
#11 /public_html/vendor/laravel/framework/src/Illuminate/Queue/QueueManager.php(291): Illuminate\Queue\SyncQueue->push('OFFLINE\\Mall\\Cl...', Array)
#12 /public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Illuminate\Queue\QueueManager->__call('push', Array)
#13 /public_html/plugins/offline/mall/classes/events/MailingEventHandler.php(129): Illuminate\Support\Facades\Facade::__callStatic('push', Array)
#14 /public_html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(441): OFFLINE\Mall\Classes\Events\MailingEventHandler->checkoutSucceeded(Object(OFFLINE\Mall\Classes\Payments\PaymentResult))
#15 /public_html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('mall.checkout.s...', Array)
#16 /public_html/vendor/october/rain/src/Events/Dispatcher.php(18): Illuminate\Events\Dispatcher->dispatch('mall.checkout.s...', Array)
#17 /public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): October\Rain\Events\Dispatcher->fire('mall.checkout.s...', Array)
#18 /public_html/plugins/offline/mall/classes/payments/PaymentRedirector.php(106): Illuminate\Support\Facades\Facade::__callStatic('fire', Array)
#19 /public_html/plugins/offline/mall/classes/payments/PaymentService.php(83): OFFLINE\Mall\Classes\Payments\PaymentRedirector->handlePaymentResult(Object(OFFLINE\Mall\Classes\Payments\PaymentResult))
#20 /public_html/plugins/offline/mall/components/QuickCheckout.php(285): OFFLINE\Mall\Classes\Payments\PaymentService->process('checkout')
#21 /public_html/modules/system/traits/DependencyMaker.php(29): OFFLINE\Mall\Components\QuickCheckout->onSubmit()
#22 /public_html/modules/cms/classes/ComponentBase.php(236): Cms\Classes\ComponentBase->makeCallMethod(Object(OFFLINE\Mall\Components\QuickCheckout), 'onSubmit')
#23 /public_html/modules/cms/classes/controller/HasAjaxRequests.php(324): Cms\Classes\ComponentBase->runAjaxHandler('onSubmit')
#24 /public_html/modules/cms/classes/controller/HasAjaxRequests.php(129): Cms\Classes\Controller->runAjaxHandler('quickCheckout::...')
#25 /public_html/modules/cms/classes/Controller.php(386): Cms\Classes\Controller->execAjaxHandlers()
#26 /public_html/modules/cms/classes/Controller.php(226): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#27 /public_html/modules/cms/classes/CmsController.php(72): Cms\Classes\Controller->run('checkout')
#28 /public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Cms\Classes\CmsController->run('checkout')
#29 /public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction('run', Array)
#30 /public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(260): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#31 /public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#32 /public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\Routing\Route->run()
#33 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /public_html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /public_html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#40 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /public_html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#48 /public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#49 /public_html/vendor/october/rain/src/Router/CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#50 /public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#51 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#52 /public_html/plugins/offline/speedy/classes/middleware/CDNMiddleware.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): OFFLINE\Speedy\Classes\Middleware\CDNMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /public_html/plugins/offline/speedy/classes/middleware/Http2Middleware.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): OFFLINE\Speedy\Classes\Middleware\Http2Middleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /public_html/plugins/offline/responsiveimages/classes/ResponsiveImagesMiddleware.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): OFFLINE\ResponsiveImages\Classes\ResponsiveImagesMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /public_html/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /public_html/plugins/vdlp/redirect/classes/RedirectMiddleware.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Vdlp\Redirect\Classes\RedirectMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#65 /public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#66 /public_html/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#67 {main}
```

**Comment by tobias-kuendig** [comment]
> Expected response code "354" but got code "250"

This seems to be an issue outside of mall and is related to your mailer setup.

I'm closing this issue since it is quite old and the problem probably has been worked around already.
