### ISSUE TITLE
Unknown column 'name' after save customerProfile

### ISSUE THREAD

**Issue by get-web** [OFFLINE-GmbH/oc-mall-plugin#1197]
OctoberCMS 3.7.5
RainLab.User 3.1.3
OFFLINE.Mall 3.5.12

When I try to save my profile, I get an error

```"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: update `users` set `name` = tester, `surname` = tester, `users`.`updated_at` = 2024-12-07 09:50:37 where `id` = 30)" on line 760 of H:\OSPanel\home\squix.local\public\vendor\laravel\framework\src\Illuminate\Database\Connection.php```

```PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' in \public\vendor\laravel\framework\src\Illuminate\Database\Connection.php:566
Stack trace:
#0 \public\vendor\laravel\framework\src\Illuminate\Database\Connection.php(566): PDO->prepare('update `users` ...')
#1 \public\vendor\laravel\framework\src\Illuminate\Database\Connection.php(753): Illuminate\Database\Connection->Illuminate\Database\{closure}('update `users` ...', Array)
#2 \public\vendor\laravel\framework\src\Illuminate\Database\Connection.php(720): Illuminate\Database\Connection->runQueryCallback('update `users` ...', Array, Object(Closure))
#3 \public\vendor\laravel\framework\src\Illuminate\Database\Connection.php(558): Illuminate\Database\Connection->run('update `users` ...', Array, Object(Closure))
#4 \public\vendor\laravel\framework\src\Illuminate\Database\Connection.php(510): Illuminate\Database\Connection->affectingStatement('update `users` ...', Array)
#5 \public\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(3356): Illuminate\Database\Connection->update('update `users` ...', Array)
#6 \public\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1011): Illuminate\Database\Query\Builder->update(Array)
#7 \public\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1214): Illuminate\Database\Eloquent\Builder->update(Array)
#8 \public\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1131): Illuminate\Database\Eloquent\Model->performUpdate(Object(October\Rain\Database\Builder))
#9 \public\vendor\october\rain\src\Database\Model.php(383): Illuminate\Database\Eloquent\Model->save(Array)
#10 \public\vendor\october\rain\src\Database\Model.php(425): October\Rain\Database\Model->saveInternal(Array)
#11 \public\plugins\offline\mall\components\CustomerProfile.php(109): October\Rain\Database\Model->save()
#12 \public\vendor\laravel\framework\src\Illuminate\Database\Concerns\ManagesTransactions.php(30): OFFLINE\Mall\Components\CustomerProfile->OFFLINE\Mall\Components\{closure}(Object(October\Rain\Database\Connections\MySqlConnection))
#13 \public\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(469): Illuminate\Database\Connection->transaction(Object(Closure))
#14 \public\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(338): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#15 \public\plugins\offline\mall\components\CustomerProfile.php(95): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#16 \public\modules\system\traits\DependencyMaker.php(29): OFFLINE\Mall\Components\CustomerProfile->onSubmit()
#17 \public\modules\cms\classes\ComponentBase.php(235): Cms\Classes\ComponentBase->makeCallMethod(Object(OFFLINE\Mall\Components\CustomerProfile), 'onSubmit')
#18 \public\modules\cms\classes\controller\HasAjaxRequests.php(324): Cms\Classes\ComponentBase->runAjaxHandler('onSubmit')
#19 \public\modules\cms\classes\Controller.php(878): Cms\Classes\Controller->Cms\Classes\Controller\{closure}()
#20 \public\modules\cms\classes\controller\HasAjaxRequests.php(323): Cms\Classes\Controller->inComponentContext(Object(OFFLINE\Mall\Components\CustomerProfile), Object(Closure))
#21 \public\modules\cms\classes\controller\HasAjaxRequests.php(129): Cms\Classes\Controller->runAjaxHandler('customerProfile...')
#22 \public\modules\cms\classes\Controller.php(386): Cms\Classes\Controller->execAjaxHandlers()
#23 \public\modules\cms\classes\Controller.php(226): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#24 \public\modules\cms\classes\CmsController.php(72): Cms\Classes\Controller->run('/user')
#25 \public\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): Cms\Classes\CmsController->run('ru/user')
#26 \public\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction('run', Array)
#27 \public\vendor\laravel\framework\src\Illuminate\Routing\Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#28 \public\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController()
#29 \public\vendor\laravel\framework\src\Illuminate\Routing\Router.php(798): Illuminate\Routing\Route->run()
#30 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 \public\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 \public\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 \public\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 \public\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#37 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 \public\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 \public\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 \public\vendor\laravel\framework\src\Illuminate\Routing\Router.php(797): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 \public\vendor\laravel\framework\src\Illuminate\Routing\Router.php(776): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#45 \public\vendor\laravel\framework\src\Illuminate\Routing\Router.php(740): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#46 \public\vendor\october\rain\src\Router\CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#47 \public\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(190): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#48 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#49 \public\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 \public\vendor\october\rain\src\Foundation\Http\Middleware\CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 \public\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(165): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 \public\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#55 \public\index.php(42): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#56 {main}

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: update `users` set `name` = tester, `surname` = tester, `users`.`updated_at` = 2024-12-07 09:50:37 where `id` = 30) in \public\vendor\laravel\framework\src\Illuminate\Database\Connection.php:760
Stack trace:
#0 \public\vendor\laravel\framework\src\Illuminate\Database\Connection.php(720): Illuminate\Database\Connection->runQueryCallback('update `users` ...', Array, Object(Closure))
#1 \public\vendor\laravel\framework\src\Illuminate\Database\Connection.php(558): Illuminate\Database\Connection->run('update `users` ...', Array, Object(Closure))
#2 \public\vendor\laravel\framework\src\Illuminate\Database\Connection.php(510): Illuminate\Database\Connection->affectingStatement('update `users` ...', Array)
#3 \public\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(3356): Illuminate\Database\Connection->update('update `users` ...', Array)
#4 \public\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1011): Illuminate\Database\Query\Builder->update(Array)
#5 \public\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1214): Illuminate\Database\Eloquent\Builder->update(Array)
#6 \public\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1131): Illuminate\Database\Eloquent\Model->performUpdate(Object(October\Rain\Database\Builder))
#7 \public\vendor\october\rain\src\Database\Model.php(383): Illuminate\Database\Eloquent\Model->save(Array)
#8 \public\vendor\october\rain\src\Database\Model.php(425): October\Rain\Database\Model->saveInternal(Array)
#9 \public\plugins\offline\mall\components\CustomerProfile.php(109): October\Rain\Database\Model->save()
#10 \public\vendor\laravel\framework\src\Illuminate\Database\Concerns\ManagesTransactions.php(30): OFFLINE\Mall\Components\CustomerProfile->OFFLINE\Mall\Components\{closure}(Object(October\Rain\Database\Connections\MySqlConnection))
#11 \public\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(469): Illuminate\Database\Connection->transaction(Object(Closure))
#12 \public\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(338): Illuminate\Database\DatabaseManager->__call('transaction', Array)
#13 \public\plugins\offline\mall\components\CustomerProfile.php(95): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#14 \public\modules\system\traits\DependencyMaker.php(29): OFFLINE\Mall\Components\CustomerProfile->onSubmit()
#15 \public\modules\cms\classes\ComponentBase.php(235): Cms\Classes\ComponentBase->makeCallMethod(Object(OFFLINE\Mall\Components\CustomerProfile), 'onSubmit')
#16 \public\modules\cms\classes\controller\HasAjaxRequests.php(324): Cms\Classes\ComponentBase->runAjaxHandler('onSubmit')
#17 \public\modules\cms\classes\Controller.php(878): Cms\Classes\Controller->Cms\Classes\Controller\{closure}()
#18 \public\modules\cms\classes\controller\HasAjaxRequests.php(323): Cms\Classes\Controller->inComponentContext(Object(OFFLINE\Mall\Components\CustomerProfile), Object(Closure))
#19 \public\modules\cms\classes\controller\HasAjaxRequests.php(129): Cms\Classes\Controller->runAjaxHandler('customerProfile...')
#20 \public\modules\cms\classes\Controller.php(386): Cms\Classes\Controller->execAjaxHandlers()
#21 \public\modules\cms\classes\Controller.php(226): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#22 \public\modules\cms\classes\CmsController.php(72): Cms\Classes\Controller->run('/user')
#23 \public\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): Cms\Classes\CmsController->run('ru/user')
#24 \public\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(43): Illuminate\Routing\Controller->callAction('run', Array)
#25 \public\vendor\laravel\framework\src\Illuminate\Routing\Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#26 \public\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController()
#27 \public\vendor\laravel\framework\src\Illuminate\Routing\Router.php(798): Illuminate\Routing\Route->run()
#28 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 \public\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 \public\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 \public\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 \public\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#35 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 \public\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 \public\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 \public\vendor\laravel\framework\src\Illuminate\Routing\Router.php(797): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 \public\vendor\laravel\framework\src\Illuminate\Routing\Router.php(776): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#43 \public\vendor\laravel\framework\src\Illuminate\Routing\Router.php(740): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#44 \public\vendor\october\rain\src\Router\CoreRouter.php(32): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#45 \public\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(190): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#46 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#47 \public\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 \public\vendor\october\rain\src\Foundation\Http\Middleware\CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 \public\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 \public\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(165): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 \public\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(134): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 \public\index.php(42): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 {main}```

**Comment by tobias-kuendig** [comment]
Thank you, this is fixed in v3.5.13.
