### ISSUE TITLE
Can't install the plugin. 

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-mall-plugin#277]
I recently can't install this plugin via the backend. I get this error: 

```
"Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)" on line 16 of /home/styleclo/public_html/deviowa/plugins/offline/mall/models/Currency.php
```

Fresh install of October. Any ideas of why this doesn't work?

**Comment by artistro08** [comment]
here's the stacktrace:

```
Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /home/styleclo/public_html/deviowa/plugins/offline/mall/classes/traits/UserSpecificPrice.php:36
Stack trace:
#0 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Support/ClassLoader.php(99): October\Rain\Support\ClassLoader->includeClass('OFFLINE\\Mall\\Cl...', 'plugins/offline...')
#1 [internal function]: October\Rain\Support\ClassLoader->load('OFFLINE\\Mall\\Cl...')
#2 /home/styleclo/public_html/deviowa/plugins/offline/mall/models/Product.php(31): spl_autoload_call('OFFLINE\\Mall\\Cl...')
#3 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Support/ClassLoader.php(130): require_once('/home/styleclo/...')
#4 /home/styleclo/public_html/deviowa/vendor/october/rain/src/Support/ClassLoader.php(99): October\Rain\Support\ClassLoader->includeClass('OFFLINE\\Mall\\Mo...', 'plugins/offline...')
#5 [internal function]: October\Rain\Support\ClassLoader->load('OFFLINE\\Mall\\Mo...')
#6 /home/styleclo/public_html/deviowa/plugins/offline/mall/classes/registration/BootEvents.php(31): spl_autoload_call('OFFLINE\\Mall\\Mo...')
#7 /home/styleclo/public_html/deviowa/plugins/offline/mall/classes/registration/BootEvents.php(22): OFFLINE\Mall\Plugin->registerObservers()
#8 /home/styleclo/public_html/deviowa/plugins/offline/mall/Plugin.php(44): OFFLINE\Mall\Plugin->registerEvents()
#9 /home/styleclo/public_html/deviowa/modules/system/classes/PluginManager.php(293): OFFLINE\Mall\Plugin->boot()
#10 /home/styleclo/public_html/deviowa/modules/system/classes/PluginManager.php(275): System\Classes\PluginManager->bootPlugin(Object(OFFLINE\Mall\Plugin))
#11 /home/styleclo/public_html/deviowa/modules/system/ServiceProvider.php(96): System\Classes\PluginManager->bootAll()
#12 [internal function]: System\ServiceProvider->boot()
#13 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#14 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(October\Rain\Foundation\Application), Array, Object(Closure))
#16 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(October\Rain\Foundation\Application), Array, Array, NULL)
#17 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(792): Illuminate\Container\Container->call(Array)
#18 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Foundation\Application->bootProvider(Object(System\ServiceProvider))
#19 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(System\ServiceProvider), 24)
#20 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): array_walk(Array, Object(Closure))
#21 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#22 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(October\Rain\Foundation\Application))
#23 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(162): Illuminate\Foundation\Application->bootstrapWith(Array)
#24 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(146): Illuminate\Foundation\Http\Kernel->bootstrap()
#25 /home/styleclo/public_html/deviowa/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#26 /home/styleclo/public_html/deviowa/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#27 {main}
```

**Comment by tobias-kuendig** [comment]
PHP 7.1 is required

Devin Green <notifications@github.com> schrieb am Do., 25. Juli 2019, 20:53:

**Comment by artistro08** [comment]
My fault then. That worked
