### ISSUE TITLE
500 Error on pages using the category component after 1.10.0 update

### ISSUE THREAD

**Issue by cssninjaStudio** [OFFLINE-GmbH/oc-mall-plugin#432]
Got a 500 error on all pages displaying the category products component after update. Is it because of the partial changes?

Here is what I found in the logs, seems to be product translation related. Any quick fix for that? iam forced to stay on maintenance as my homepage and category pages don"t work.

```
[2020-01-18 00:21:42] development.ERROR: Illuminate\Database\Eloquent\RelationNotFoundException: Call to undefined relationship [translations] on model [OFFLINE\Mall\Models\Product]. in /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/RelationNotFoundException.php:34
Stack trace:
#0 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(548): Illuminate\Database\Eloquent\RelationNotFoundException::make(Object(OFFLINE\Mall\Models\Product), 'translations')
#1 [internal function]: Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}()
#2 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(89): call_user_func(Object(Closure))
#3 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(550): Illuminate\Database\Eloquent\Relations\Relation::noConstraints(Object(Closure))
#4 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(518): Illuminate\Database\Eloquent\Builder->getRelation('translations')
#5 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(498): Illuminate\Database\Eloquent\Builder->eagerLoadRelation(Array, 'translations', Object(Closure))
#6 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(466): Illuminate\Database\Eloquent\Builder->eagerLoadRelations(Array)
#7 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(307): Illuminate\Database\Eloquent\Builder->get(Array)
#8 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(288): Illuminate\Database\Eloquent\Builder->findMany(Array, Array)
#9 /home/cssninjaua/www/plugins/offline/mall/components/Products.php(400): Illuminate\Database\Eloquent\Builder->find(Array)
#10 /home/cssninjaua/www/plugins/offline/mall/components/Products.php(357): OFFLINE\Mall\Components\Products->getGhosts(Array)
#11 /home/cssninjaua/www/plugins/offline/mall/components/Products.php(259): OFFLINE\Mall\Components\Products->getItems()
#12 /home/cssninjaua/www/plugins/offline/mall/components/Products.php(272): OFFLINE\Mall\Components\Products->setData()
#13 /home/cssninjaua/www/modules/cms/classes/CmsCompoundObject.php(168): OFFLINE\Mall\Components\Products->onRun()
#14 /home/cssninjaua/www/modules/cms/classes/Controller.php(499): Cms\Classes\CmsCompoundObject->runComponents()
#15 /home/cssninjaua/www/modules/cms/classes/Controller.php(392): Cms\Classes\Controller->execPageCycle()
#16 /home/cssninjaua/www/modules/cms/classes/Controller.php(223): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#17 /home/cssninjaua/www/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run('category/all')
#18 [internal function]: Cms\Classes\CmsController->run('category/all')
#19 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#20 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#21 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#22 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\Routing\Route->runController()
#23 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Route->run()
#24 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#43 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#44 /home/cssninjaua/www/vendor/october/rain/src/Router/CoreRouter.php(20): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#45 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#46 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#47 /home/cssninjaua/www/plugins/offline/speedy/classes/middleware/CDNMiddleware.php(40): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): OFFLINE\Speedy\Classes\Middleware\CDNMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /home/cssninjaua/www/plugins/offline/speedy/classes/middleware/Http2Middleware.php(38): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): OFFLINE\Speedy\Classes\Middleware\Http2Middleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /home/cssninjaua/www/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(24): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#59 /home/cssninjaua/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#60 /home/cssninjaua/www/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#61 {main}
```

**Comment by cssninjaStudio** [comment]
Looks like I solved with by installing Rainlab translate plugin. has it become a mandatory dependency?

**Comment by tobias-kuendig** [comment]
What's the error?

cssninja <notifications@github.com> schrieb am Sa., 18. Jan. 2020, 01:05:

**Comment by tobias-kuendig** [comment]
Thank you very much for this report! I honestly forgot about supporting RainLab.Translate as an optional dependency when adding the improvements in the latest two versions.

I just decided to make RainLab.Translate a hard dependency starting from version 1.11. The code just becomes unnecessary complex with all the optional stuff. Also, the Translate plugin mostly stays out of your way if you don't add a second locale.

The fix for the time being is just installing the translate plugin and everything should work again.

This issue is currently blocked by https://github.com/rainlab/translate-plugin/issues/539

**Comment by tobias-kuendig** [comment]
This problem has been fixed upstream. Thank you for this report!
