### ISSUE TITLE
Cart exception

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-mall-plugin#529]
I am in the midst of developing a MALL Restful API.

Trying to get the cart for an anonymous user raises this exception for which I have no explanation.
Any idea why this `cart_session_id` would be 368 characters long?

in my APi routes, I added the middleware `web` to have the web session managed.

code in my API controller that raises the exception:

```php
        $this->cart = CartModel::byUser($this->user);
```

the SQL Statement looks like

```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column &#039;session_id&#039; at
				row 1 (SQL: insert into `offline_mall_carts` (`session_id`, `updated_at`, `created_at`) values
				(eyJpdiI6InFvdytGNldVMlpoRDNDUWFNam5mVlE9PSIsInZhbHVlIjoiXC80WjJMTEc1M1wvZDFkdHBjUlBLNXZEYkRId1FiTlwveG9hUFIrTFE0WjNEVFVcL0tjNExBS0d4Mis5S0twXC9uTlV5d2JVc0o4a0FScSsyd2VXb1VYTHo3OGgzdGpvWmhWenJrbUhOVkNNa2kxOXhGQW5CaUFodldnNW9kRzVOK05kT0d5MDR4Uk1RTWF6RGUwTmlLWEFERVE9PSIsIm1hYyI6IjQ4ZWYzMzM3ZGMyYzhlMzU0NzI4MmZkZDU3NGU4NTQwMTAxYzE3NTM1Mzc5NjhlY2IyZDQxMDg4YTMwZGI5ZmUifQ==,
				2020-06-26 05:45:47, 2020-06-26 05:45:47))
```

and the exception

```php
[2020-06-26 05:41:02] development.ERROR: PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'session_id' at row 1 in /Users/christophevidal/Sites/oc-shop-demo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
#0 /Users/christophevidal/Sites/oc-shop-demo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL)
#1 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(458): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `of...', Array)
#3 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into `of...', Array, Object(Closure))
#4 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\Database\Connection->run('insert into `of...', Array, Object(Closure))
#5 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\Database\Connection->statement('insert into `of...', Array)
#6 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `of...', Array)
#7 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2159): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(October\Rain\Database\QueryBuilder), 'insert into `of...', Array, 'id')
#8 /Users/christophevidal/Sites/oc-shop-demo/vendor/october/rain/src/Database/QueryBuilder.php(278): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#9 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1283): October\Rain\Database\QueryBuilder->insertGetId(Array, 'id')
#10 /Users/christophevidal/Sites/oc-shop-demo/vendor/october/rain/src/Database/Builder.php(202): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#11 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(722): October\Rain\Database\Builder->__call('insertGetId', Array)
#12 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(687): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(October\Rain\Database\Builder), Array)
#13 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(550): Illuminate\Database\Eloquent\Model->performInsert(Object(October\Rain\Database\Builder))
#14 /Users/christophevidal/Sites/oc-shop-demo/vendor/october/rain/src/Database/Model.php(761): Illuminate\Database\Eloquent\Model->save(Array)
#15 /Users/christophevidal/Sites/oc-shop-demo/vendor/october/rain/src/Database/Model.php(794): October\Rain\Database\Model->saveInternal(Array)
#16 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(382): October\Rain\Database\Model->save()
#17 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Support/helpers.php(1038): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(OFFLINE\Mall\Models\Cart))
#18 /Users/christophevidal/Sites/oc-shop-demo/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(383): tap(Object(OFFLINE\Mall\Models\Cart), Object(Closure))
#19 /Users/christophevidal/Sites/oc-shop-demo/plugins/offline/mall/classes/traits/cart/CartSession.php(50): Illuminate\Database\Eloquent\Builder->firstOrCreate(Array)
#20 /Users/christophevidal/Sites/oc-shop-demo/plugins/offline/mall/classes/traits/cart/CartSession.php(17): OFFLINE\Mall\Models\Cart::bySession()
#21 /Users/christophevidal/Sites/oc-shop-demo/plugins/voilaah/mallapi/http/api/ShoppingCartController.php(45): OFFLINE\Mall\Models\Cart::byUser(NULL)
#22 /Users/christophevidal/Sites/oc-shop-demo/plugins/voilaah/mallapi/http/api/ShoppingCartController.php(35): Voilaah\MallApi\Http\Api\ShoppingCartController->setData()
```

**Comment by tobias-kuendig** [comment]
Strings that start with `ey` are ususally encrypted payloads (encrypted by the `crypt` function, for example).

Would it be possible that `$sessionId` is using the Cookie in this case (`Session::get('cart_session_id')` would return null)?
https://github.com/OFFLINE-GmbH/oc-mall-plugin/blob/develop/classes/traits/cart/CartSession.php#L46

It's possible that we fetch the Cookie and that gets encrypted by default in Laravel since a few versions ago. This is definitely a bug then.

**Comment by tobias-kuendig** [comment]
How did you register your route/middleware? The `web` middleware should take care of the cookie decryption.

This test in a `routes.php` works for me:

```php
Route::get('/test', function () {

    dd(Cart::byUser(\Auth::getUser()));

})->middleware('web');
```

Removing the `->middleware()` call will result in the error message you have posted. Without the middleware the encrypted cookie value is used.

**Comment by chrisvidal** [comment]
I am using the middleware `web` in my route indeed.

```php
Route::group([
        'middleware' => ['web'],
        'prefix' => 'api/mall',
        'namespace' => 'Voilaah\MallApi\Http\Api'
    ], function () {
```

**Comment by tobias-kuendig** [comment]
This works as well! Do you override the middleware in your controller by accident?

```php
Route::group([
    'middleware' => ['web'],
    'prefix' => 'api',
], function () {
    Route::get('/test', function () {
        dd(Cart::byUser(\Auth::getUser()));
    });
});
```

**Comment by chrisvidal** [comment]
Mmm I am using the RLuders JWT Auth plugin that must be overriding the
middleware somewhere I guess.


Christophe Vidal
C.T.O. at  Voilaah
A  29B Mosque Street, Singapore 059507
W  http://voilaah.com  <http://voilaah.com>

Create your own WiseStamp email signature
<https://www.wisestamp.com/signature-in-email/?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=6647088060039168>

**Comment by chrisvidal** [comment]
here is my routes

```php
<?php

Route::group([
        'middleware' => ['web'],
        'prefix' => 'api/mall',
        'namespace' => 'Voilaah\MallApi\Http\Api'
    ], function () {

    /* testing the API */
    Route::resource('ping', 'Ping');

    Route::group([
        'middleware' => ['jwt.auth'],
        'prefix' => 'auth/me'
    ], function() {

        Route::get(
            'profile',
            'CustomerController'
        )->name('customer.profile');
   
   });

  ....

   Route::apiResource('cart', 'ShoppingCartController');

});

**Comment by tobias-kuendig** [comment]
Would adding the `EncryptCookie` middleware explicitly solve this problem?

```php
     Route::group([
        'middleware' => ['jwt.auth', \October\Rain\Cookie\Middleware\EncryptCookies::class],
        'prefix' => 'auth/me'
    ], function() {

        Route::get(
            'profile',
            'CustomerController'
        )->name('customer.profile');
   
   });
```

**Comment by tobias-kuendig** [comment]
I'm closing this issue due to inactivity. If you need any further assistance feel free to reply.
