### ISSUE TITLE
When I added new repo I get error

### ISSUE THREAD

**Issue by sizucen** [OFFLINE-GmbH/oc-mall-plugin#652]
I added "alegra/omnipay-iyzico" in composer.json. When I add run this composer I get problems. What is problem? I wanna add new Payment Method (Iyzico) but I can't do it.

```
PHP Fatal error:  Declaration of Illuminate\Cache\Repository::add($key, $value, $minutes) must be compatible with Illuminate\Contracts\Cache\Repository::add($key, $value, $ttl = NULL) in C:\xampp\htdocs\oc\vendor\laravel\framework\src\Illuminate\Cache\Repository.php on line 239
PHP Fatal error:  Uncaught Error: Class 'Illuminate\Cache\Repository' not found in C:\xampp\htdocs\oc\vendor\laravel\framework\src\Illuminate\Cache\CacheManager.php:227
Stack trace:
#0 C:\xampp\htdocs\oc\vendor\laravel\framework\src\Illuminate\Cache\CacheManager.php(154): Illuminate\Cache\CacheManager->repository(Object(Illuminate\Cache\FileStore))
#1 C:\xampp\htdocs\oc\vendor\laravel\framework\src\Illuminate\Cache\CacheManager.php(105): Illuminate\Cache\CacheManager->createFileDriver(Array)
#2 C:\xampp\htdocs\oc\vendor\laravel\framework\src\Illuminate\Cache\CacheManager.php(80): Illuminate\Cache\CacheManager->resolve('file')
#3 C:\xampp\htdocs\oc\vendor\laravel\framework\src\Illuminate\Cache\CacheManager.php(58): Illuminate\Cache\CacheManager->get('file')
#4 C:\xampp\htdocs\oc\vendor\laravel\framework\src\Illuminate\Cache\CacheManager.php(304): Illuminate\Cache\CacheManager->store()
#5 C:\xampp\htdocs\oc\vendor\october\rain\src\Database\QueryBuilder.php(158): Illuminate\Cache\CacheManager->__call('remember', Array)
#6 C:\xamp in C:\xampp\htdocs\oc\vendor\laravel\framework\src\Illuminate\Cache\CacheManager.php on line 227
```

**Comment by tobias-kuendig** [comment]
You are importing different laravel/framework versions. Make sure you run `composer install` only from the root directory of your project. Also remove all other `vendor` folders inside any plugin directory.

**Comment by sizucen** [comment]
> You are importing different laravel/framework versions. Make sure you run `composer install` only from the root directory of your project. Also remove all other `vendor` folders inside any plugin directory.

This my edit composer.json. Where is wrong?

`
{
  "name": "offline/oc-mall-plugin",
  "type": "october-plugin",
  "description": "E-commerce solution for October CMS",
  "keywords": [
    "october",
    "cms",
    "e-commerce",
    "shop",
    "plugin"
  ],
  "license": "MIT",
  "authors": [
    {
      "name": "Tobias Kündig",
      "email": "tobias@offline.ch"
    }
  ],
  "require": {
    "composer/installers": "~1.0",
    "hashids/hashids": "^2.0",
    "tmarois/filebase": "^1.0",
    "offline/jsonq": "^5.2.4",
    "illuminate/support": "5.5.*|6.*",
    "elasticsearch/elasticsearch": "^6.0",
    "league/omnipay": "^3",
    "omnipay/paypal": "^3.0",
    "omnipay/stripe": "^3.0",
    "vitalybaev/google-merchant-feed": "^1.1",
    "barryvdh/laravel-dompdf": "^0.8.5",
    "bummzack/omnipay-postfinance": "dev-master",
    **"alegra/omnipay-iyzico": "*"**
  },
  "require-dev": {
    "squizlabs/php_codesniffer": "*",
    "phpmd/phpmd": "^2.6",
    "mockery/mockery": "^1.0"
  }
}
`

**Comment by tobias-kuendig** [comment]
Were you able to solve this issue? The problem is that there is a plugin importing a different laravel version than October requires. I cannot tell you what plugin it is. 

Usually, this can be solved by deleting all `vendor` directories inside the `plugins/**` path and deleting you `composer.lock` file in the root of your project. Then run `composer install` from the root directory again to install all dependencies.

**Comment by tobias-kuendig** [comment]
I'm closing this issue due to inactivity. If you need any further assistance feel free to reply.
