### ISSUE TITLE
Exception while upgrading to 1.13.0

### ISSUE THREAD

**Issue by Eoler** [OFFLINE-GmbH/oc-mall-plugin#693]
Its probably unquoted entry in `version.yaml`:

```
Plugin version: 1.12.3
PHP: 7.4.11
MariaDB: 10.1.47-MariaDB-0ubuntu0.18.04.1
---
ErrorException: preg_match() expects parameter 2 to be string, array given in /home/users/hugpunch/www/pubdev_html/modules/system/classes/VersionManager.php:563
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/users/hugpunch/www/pubdev_html/modules/system/classes/VersionManager.php(563): preg_match()
#2 [internal function]: System\Classes\VersionManager->System\Classes\{closure}()
#3 /home/users/hugpunch/www/pubdev_html/modules/system/classes/VersionManager.php(564): array_filter()
#4 /home/users/hugpunch/www/pubdev_html/modules/system/classes/VersionManager.php(129): System\Classes\VersionManager->extractScriptsAndComments()
#5 /home/users/hugpunch/www/pubdev_html/modules/system/classes/VersionManager.php(99): System\Classes\VersionManager->applyPluginUpdate()
#6 /home/users/hugpunch/www/pubdev_html/modules/system/classes/UpdateManager.php(523): System\Classes\VersionManager->updatePlugin()
#7 /home/users/hugpunch/www/pubdev_html/modules/system/classes/UpdateManager.php(154): System\Classes\UpdateManager->updatePlugin()
#8 /home/users/hugpunch/www/pubdev_html/modules/system/controllers/Updates.php(330): System\Classes\UpdateManager->update()
#9 [internal function]: System\Controllers\Updates->onExecuteStep()
(...)
```

**Comment by tobias-kuendig** [comment]
It is, thank you  @Eoler. Fixed in bbddca2f9f54fef4e301322f317e99d6c878200f.
