### ISSUE TITLE
Exception: "Class 'Filebase\Database' not found" after update (1.14.0)

### ISSUE THREAD

**Issue by aminusmin** [OFFLINE-GmbH/oc-mall-plugin#776]
after the update I get an error.  Exception: "Class 'Filebase\Database' not found" after update (1.14.0)
db is sqlite.

```
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Filebase\Database' not found in /Users/amin/Sites/mall/plugins/offline/mall/classes/index/Filebase.php:23
Stack trace:
#0 /Users/amin/Sites/mall/plugins/offline/mall/classes/registration/BootServiceContainer.php(69): OFFLINE\Mall\Classes\Index\Filebase->__construct()
#1 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): OFFLINE\Mall\Plugin->OFFLINE\Mall\Classes\Registration\{closure}(Object(October\Rain\Foundation\Application), Array)
#2 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\Container\Container->build(Object(Closure))
#3 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\Container\Container->resolve('OFFLINE\\Mall\\Cl...', Array, true)
#4 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\Foundation\Application->resolve('OFFLINE\\Mall\\Cl...', Array)
#5 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\Container\Container->make('OFFLINE\\Mall\\Cl...', Array)
#6 /Users/amin/Sites/mall/vendor/october/rain/src/Foundation/Application.php(214): Illuminate\Foundation\Application->make('OFFLINE\\Mall\\Cl...')
#7 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(120): October\Rain\Foundation\Application->make('OFFLINE\\Mall\\Cl...', Array)
#8 /Users/amin/Sites/mall/plugins/offline/mall/components/Products.php(349): app('OFFLINE\\Mall\\Cl...')
#9 /Users/amin/Sites/mall/plugins/offline/mall/components/Products.php(259): OFFLINE\Mall\Components\Products->getItems()
#10 /Users/amin/Sites/mall/plugins/offline/mall/components/Products.php(272): OFFLINE\Mall\Components\Products->setData()
#11 /Users/amin/Sites/mall/modules/cms/Classes/CmsCompoundObject.php(185): OFFLINE\Mall\Components\Products->onRun()
#12 /Users/amin/Sites/mall/modules/cms/Classes/Controller.php(1100): Cms\Classes\CmsCompoundObject->runComponents()
#13 /Users/amin/Sites/mall/modules/cms/Twig/Extension.php(102): Cms\Classes\Controller->renderPartial('products', Array, true)
#14 /Users/amin/Sites/mall/vendor/twig/twig/src/Environment.php(418) : eval()'d code(119): Cms\Twig\Extension->partialFunction('demo/demo-page', Array, true)
#15 /Users/amin/Sites/mall/vendor/twig/twig/src/Template.php(405): __TwigTemplate_ffc23bd2a0b1607244df4fce4d4eb2086d53f23c0b558b2d06d144be97565f87->doDisplay(Array, Array)
#16 /Users/amin/Sites/mall/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /Users/amin/Sites/mall/vendor/twig/twig/src/Template.php(390): Twig\Template->display(Array)
#18 /Users/amin/Sites/mall/modules/cms/Classes/Controller.php(433): Twig\Template->render(Array)
#19 /Users/amin/Sites/mall/modules/cms/Classes/Controller.php(225): Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#20 /Users/amin/Sites/mall/modules/cms/Classes/CmsController.php(50): Cms\Classes\Controller->run('/')
#21 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Cms\Classes\CmsController->run('/')
#22 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('run', Array)
#23 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#24 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\Routing\Route->runController()
#25 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\Routing\Route->run()
#26 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /Users/amin/Sites/mall/plugins/rainlab/translate/classes/LocaleMiddleware.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): RainLab\Translate\Classes\LocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#41 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#42 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#43 /Users/amin/Sites/mall/vendor/october/rain/src/Router/CoreRouter.php(25): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#44 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#45 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#46 /Users/amin/Sites/mall/plugins/offline/speedy/classes/middleware/CDNMiddleware.php(40): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): OFFLINE\Speedy\Classes\Middleware\CDNMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /Users/amin/Sites/mall/plugins/offline/speedy/classes/middleware/Http2Middleware.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): OFFLINE\Speedy\Classes\Middleware\Http2Middleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /Users/amin/Sites/mall/plugins/offline/responsiveimages/classes/ResponsiveImagesMiddleware.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): OFFLINE\ResponsiveImages\Classes\ResponsiveImagesMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /Users/amin/Sites/mall/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /Users/amin/Sites/mall/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#58 /Users/amin/Sites/mall/index.php(43): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#59 {main}
```

**Comment by tobias-kuendig** [comment]
Thank you for this report. Please check out the changelog:
https://offline-gmbh.github.io/oc-mall-plugin/changelog/1.14.0.html

Ìf you use the filesystem index you need to install `offline/jsonq` and `tmarois/filebase` manually after this update.

try:

```
composer require offline/jsonq tmarois/filebase
```

**Comment by aminusmin** [comment]
sorry, my bad. it is working again. Thanks
