### ISSUE TITLE
Call to undefined method MailingEventHandler

### ISSUE THREAD

**Issue by LazyCloner** [OFFLINE-GmbH/oc-mall-plugin#952]
Hi there ! 

I'm using the mall plugin and when a user tries to create an account, I got the error `Call to undefined method OFFLINE\Mall\Classes\Events\MailingEventHandler::__invoke()`

I didn't have this issue few months before. I think it's since recent updates.

<details>
  <summary>Here is the stack trace :</summary>
  
  ```
Error: Call to undefined method OFFLINE\Mall\Classes\Events\MailingEventHandler::__invoke() in /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:441
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(249): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}()
#1 /var/www/html/vendor/october/rain/src/Events/PriorityDispatcher.php(94): Illuminate\Events\Dispatcher->dispatch()
#2 /var/www/html/vendor/october/rain/src/Events/PriorityDispatcher.php(61): October\Rain\Events\PriorityDispatcher->fireEvent()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): October\Rain\Events\PriorityDispatcher->fire()
#4 /var/www/html/plugins/offline/mall/classes/customer/DefaultSignUpHandler.php(93): Illuminate\Support\Facades\Facade::__callStatic()
#5 /var/www/html/plugins/offline/mall/classes/customer/DefaultSignUpHandler.php(29): OFFLINE\Mall\Classes\Customer\DefaultSignUpHandler->signUp()
#6 /var/www/html/plugins/offline/mall/components/SignUp.php(100): OFFLINE\Mall\Classes\Customer\DefaultSignUpHandler->handle()
#7 /var/www/html/modules/system/traits/DependencyMaker.php(29): OFFLINE\Mall\Components\SignUp->onSignUp()
#8 /var/www/html/modules/cms/classes/ComponentBase.php(197): Cms\Classes\ComponentBase->makeCallMethod()
#9 /var/www/html/modules/cms/classes/Controller.php(879): Cms\Classes\ComponentBase->runAjaxHandler()
#10 /var/www/html/modules/cms/classes/Controller.php(712): Cms\Classes\Controller->runAjaxHandler()
#11 /var/www/html/modules/cms/classes/Controller.php(363): Cms\Classes\Controller->execAjaxHandlers()
#12 /var/www/html/modules/cms/classes/Controller.php(218): Cms\Classes\Controller->runPage()
#13 /var/www/html/modules/cms/classes/CmsController.php(50): Cms\Classes\Controller->run()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Cms\Classes\CmsController->run()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\Routing\ControllerDispatcher->dispatch()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\Route->runController()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\Routing\Route->run()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /var/www/html/plugins/rainlab/translate/classes/LocaleMiddleware.php(29): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): RainLab\Translate\Classes\LocaleMiddleware->handle()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\Pipeline\Pipeline->then()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\Routing\Router->runRouteWithinStack()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\Routing\Router->runRoute()
#37 /var/www/html/vendor/october/rain/src/Router/CoreRouter.php(31): Illuminate\Routing\Router->dispatchToRoute()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): October\Rain\Router\CoreRouter->dispatch()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /var/www/html/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(23): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#46 /var/www/html/index.php(43): Illuminate\Foundation\Http\Kernel->handle()
#47 {main}

  ```
  
</details>

I'm using October 3.0.70
Mall plugin 2.0.7
PHP 8.1.9
and Composer 2.4.1

Thank you so much for your help :)

**Comment by webBook-cz** [comment]
I'm also getting this error but still I haven't find out a solution.

**Comment by xyzqtc** [comment]
Same

**Comment by LazyCloner** [comment]
#962 Fixed my issue. 
Thx !
